language: python

cache:
  - pip

services:
  - mongodb

python:
    - "2.7"
    
before_install:
    - pip install -r requirements.txt

script:
  mkdir data
  mongod --fork --logpath log_mongodb --dbpath data/
  python storeTweetsInMongoDBUsingTweepy.py
